### ISSUE TITLE
Grid-based crude oil entity placement with better spacing

### ISSUE THREAD

**Issue by h8ul-modder** [h8ul-modder/factorio-ribbon-maze#10]
Oil entities spawn too close together and can't all be connected to pipes at once. They should spawn more like vanilla oil.

https://www.reddit.com/r/factorio/comments/9zngqj/new_mod_ribbon_maze/eahbogc?utm_source=reddit-android

**Comment by Petkip** [comment]
https://mods.factorio.com/mod/Oil%20Patches%20Organizer

maybe this is of help? 

i think it fits with the squareness of the ore patchesm ir us ut to neatly organized

**Comment by h8ul-modder** [comment]
It would actually be simpler! I tried to make it look a bit more natural, because early on I intended to make the ore patches more natural too. So I think you're right I'll use a strict grid. That way you can blueprint oil too
